version: '2'
services:
  postgres:
    image: postgres:11
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: booking
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
